### ISSUE TITLE
@testsetup example in README does not work

### ISSUE THREAD

**Issue by okartal** [JuliaTesting/ReTestItems.jl#154] opened 2024-04-12 11:29 UTC
If I run

```julia
@testsetup module TestIrrationals
    export PI, area
    const PI = 3.14159
    area(radius) = PI * radius^2
end
@testitem "Arithmetic" setup=[TestIrrationals] begin
    @test 1 / PI ≈ 0.31831 atol=1e-6
end
@testitem "Geometry" setup=[TestIrrationals] begin
    @test area(1) ≈ PI
end
```

I get

```
  Test threw exception
  Expression: area(1) ≈ PI
  UndefVarError: `area` not defined
```

A am on Julia 1.10,2 and my test environment has ReTestItems v1.23.1, TestItems v0.1.1, and Test installed.

**Comment by nickrobinson251** [comment] 2024-04-12 11:39
i can't reproduce this with Julia 1.10.2 and ReTestItems v1.23.1

But you mention TestItems v0.1.1 and i suspect that's the problem. ReTestItems.jl is an alternative to TestItems.jl. Can you try removing TestItems.jl and see if that fixes things for you?

**Comment by okartal** [comment] 2024-04-12 11:54
Fantastic, that was the solution - can I also remove Test as a dependency then?  I think, the documentation of the testitems-based testing can be improved, and I would gladly help. Thank you!

**Comment by okartal** [comment] 2024-04-12 11:58
But now, it seems that the Test explorer in VSCode does not pick up the setup and running individual tests is not possible anymore. Is this known?

**Comment by nickrobinson251** [comment] 2024-04-12 16:32
yes, the VS Code integration relies on TestItems.jl (+ related packages) which don't yet support `@testsetup`

ideally one day the implementations/functionality between ReTestItems.jl and TestItems.jl would be unified, but right now they're separate

**Comment by nickrobinson251** [comment] 2024-05-03 22:15
PRs to improve docs always welcome. And feel free to open an issue again for any other problems you run into. closing this one.

**Closed by nickrobinson251** 2024-05-03 22:15 UTC
